version: '3.7'

services:
  web:
    build:
      context: .
    ports:
      - 1111

  nginx:
    build:
      context: ./nginx
    ports:
      - 443
    depends_on:
      - web
    
  cypress:
    build:
      context: .
      dockerfile: cypress/Dockerfile 
    depends_on:
      - nginx
    command: --browser chrome
    