version: '3.7'

services:
  web-1:
    build:
      context: .
    image: web-demo
    ports:
      - 1111:1111
    networks:
      - net-1

  nginx:
    build:
      context: ./nginx
    ports:
      - 443:443
    networks:
      - net-1
    depends_on:
      - web-1

  web-2:
    build:
      context: .
    image: web-demo
    ports:
      - 1112:1111
    networks:
      - net-2

networks:
  net-1:
    driver: bridge
  net-2:
    driver: bridge
