name: Web Demo [Actions]
on: workflow_dispatch
jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Start Web Server 
        uses: ./

      - name: Start nginx
        uses: ./nginx/

      - name: Test
        uses: ./cypress